/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces_Graficas.Ex06;
import javax.swing.ButtonGroup;

/**
 *
 * @author 843539
 */
public class LanchoneteForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LanchoneteForm.class.getName());

    /**
     * Creates new form LanchoneteForm
     */
    public LanchoneteForm() 
    {
        initComponents();
        this.setTitle("Faça seu pedido");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        ButtonGroup bg = new ButtonGroup();
        bg.add(rdbHamburger);
        bg.add(rdbXburger);
        bg.add(rdbXtudo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPedido = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        lblLanche = new javax.swing.JLabel();
        rdbHamburger = new javax.swing.JRadioButton();
        rdbXburger = new javax.swing.JRadioButton();
        rdbXtudo = new javax.swing.JRadioButton();
        lblAdicionais = new javax.swing.JLabel();
        chkQueijo = new javax.swing.JCheckBox();
        chkBacon = new javax.swing.JCheckBox();
        chkRefrigerante = new javax.swing.JCheckBox();
        btnPedido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPedido.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPedido.setForeground(java.awt.Color.blue);
        lblPedido.setText("Faça seu pedido");

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNome.setText("Seu nome");

        lblLanche.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLanche.setText("Escolha um lanche");

        rdbHamburger.setText("Hamburger (R$ 20,00)");

        rdbXburger.setText("X-Burger (R$ 25,00)");

        rdbXtudo.setText("X-Tudo (R$ 30,00)");

        lblAdicionais.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAdicionais.setText("Adicionais (opcional)");

        chkQueijo.setText("Queijo extra (R$ 5,00)");

        chkBacon.setText("Bacon (R$ 5,00)");

        chkRefrigerante.setText("Refrigerante (R$ 10,00)");

        btnPedido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPedido.setForeground(java.awt.Color.blue);
        btnPedido.setText("Fazer pedido");
        btnPedido.addActionListener(this::btnPedidoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNome)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLanche)
                                    .addComponent(rdbHamburger)
                                    .addComponent(rdbXburger)
                                    .addComponent(rdbXtudo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkRefrigerante)
                                    .addComponent(chkBacon)
                                    .addComponent(chkQueijo)
                                    .addComponent(lblAdicionais)))))
                    .addComponent(lblPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(btnPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLanche)
                    .addComponent(lblAdicionais))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbHamburger)
                    .addComponent(chkQueijo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbXburger)
                    .addComponent(chkBacon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbXtudo)
                    .addComponent(chkRefrigerante))
                .addGap(18, 18, 18)
                .addComponent(btnPedido)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoActionPerformed
        Pedido pd = new Pedido(0.0, String.format("Nome do cliente: %s\n", txtNome.getText()));
        pd.processar_lanche(rdbHamburger.isSelected(), rdbXburger.isSelected(), rdbXtudo.isSelected());
        pd.processar_adicionais(chkQueijo.isSelected(), chkBacon.isSelected(), chkRefrigerante.isSelected());        
        pd.gerar_resumo();
    }//GEN-LAST:event_btnPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LanchoneteForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPedido;
    private javax.swing.JCheckBox chkBacon;
    private javax.swing.JCheckBox chkQueijo;
    private javax.swing.JCheckBox chkRefrigerante;
    private javax.swing.JLabel lblAdicionais;
    private javax.swing.JLabel lblLanche;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPedido;
    private javax.swing.JRadioButton rdbHamburger;
    private javax.swing.JRadioButton rdbXburger;
    private javax.swing.JRadioButton rdbXtudo;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
