package Interfaces_Graficas.Ex04;
import javax.swing.JOptionPane;

public class CalculadoraForm extends javax.swing.JFrame 
{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalculadoraForm.class.getName());

    /**
     * Creates new form CalculadoraForm
     */
    public CalculadoraForm() 
    {
        initComponents();
        
        this.setTitle("Calculadora de IMC");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblCalculadora = new javax.swing.JLabel();
        LblAltura = new javax.swing.JLabel();
        TxtAltura = new javax.swing.JTextField();
        LblPeso = new javax.swing.JLabel();
        TxtPeso = new javax.swing.JTextField();
        BtnCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblCalculadora.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        LblCalculadora.setForeground(java.awt.Color.blue);
        LblCalculadora.setText("Calculadora de IMC");

        LblAltura.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblAltura.setForeground(java.awt.Color.blue);
        LblAltura.setText("Digite sua altura (em metros)");

        TxtAltura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        LblPeso.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblPeso.setForeground(java.awt.Color.blue);
        LblPeso.setText("Digite seu peso (em KG)");

        TxtPeso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TxtPeso.addActionListener(this::TxtPesoActionPerformed);

        BtnCalcular.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnCalcular.setForeground(java.awt.Color.blue);
        BtnCalcular.setText("Calcular");
        BtnCalcular.addActionListener(this::BtnCalcularActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblCalculadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(BtnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblCalculadora, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LblPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LblAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(BtnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalcularActionPerformed
        // TODO add your handling code here:
        
        String str_peso = TxtPeso.getText();
        String str_altura = TxtAltura.getText();
        
        if(str_peso.contains(","))
            str_peso = str_peso.replace(",", ".");
        if(str_altura.contains(","))
            str_altura = str_altura.replace(",", ".");
        
       try
       {
           Calculadora calc = new Calculadora(Double.parseDouble(str_peso), Double.parseDouble(str_altura));
           
           double imc = calc.calculoIMC();
           String saida = String.format("Peso: %.2fkg\nAltura: %.2fm\nIMC: %.1f\n", 
                   calc.getPeso(), calc.getAltura(), imc);
           
           JOptionPane.showMessageDialog(null, saida);
           limpar();
       }
       catch(NumberFormatException e)
       {
           JOptionPane.showMessageDialog(null,"Erro: peso e/ou altura em formato inválido", 
                    "Erro", JOptionPane.ERROR_MESSAGE);
           limpar();
       }
    }//GEN-LAST:event_BtnCalcularActionPerformed

    public void limpar()
    {
        TxtPeso.setText(null);
        TxtAltura.setText(null);
        TxtPeso.requestFocus();
    }
    
    private void TxtPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPesoActionPerformed
       
    }//GEN-LAST:event_TxtPesoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CalculadoraForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCalcular;
    private javax.swing.JLabel LblAltura;
    private javax.swing.JLabel LblCalculadora;
    private javax.swing.JLabel LblPeso;
    private javax.swing.JTextField TxtAltura;
    private javax.swing.JTextField TxtPeso;
    // End of variables declaration//GEN-END:variables
}
