/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces_Graficas.Ex05;
import javax.swing.JOptionPane;

/**
 *
 * @author CLAUDINEI
 */
public class ConsumoForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConsumoForm.class.getName());

    /**
     * Creates new form ConsumoForm
     */
    public ConsumoForm() 
    {
        initComponents();
        this.setTitle("Cálculo de Consumo");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblCalcCon = new javax.swing.JLabel();
        LblDistancia = new javax.swing.JLabel();
        TxtCombustivel = new javax.swing.JTextField();
        LblCombustivel = new javax.swing.JLabel();
        TxtDistancia = new javax.swing.JTextField();
        LblConsumo = new javax.swing.JLabel();
        TxtConsumo = new javax.swing.JTextField();
        BtnLimpar = new javax.swing.JButton();
        BtnCalcCon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblCalcCon.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        LblCalcCon.setForeground(java.awt.Color.blue);
        LblCalcCon.setText("Calculo de Consumo");

        LblDistancia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblDistancia.setForeground(java.awt.Color.blue);
        LblDistancia.setText("Informe a distância percorrida (em km)");

        TxtCombustivel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TxtCombustivel.addActionListener(this::TxtCombustivelActionPerformed);

        LblCombustivel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblCombustivel.setForeground(java.awt.Color.blue);
        LblCombustivel.setText("Informe o total de combustível gasto (em L)");

        TxtDistancia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TxtDistancia.addActionListener(this::TxtDistanciaActionPerformed);

        LblConsumo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblConsumo.setForeground(java.awt.Color.blue);
        LblConsumo.setText("Média de consumo (em km/L)");

        TxtConsumo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TxtConsumo.addActionListener(this::TxtConsumoActionPerformed);

        BtnLimpar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnLimpar.setForeground(java.awt.Color.blue);
        BtnLimpar.setText("Limpar");
        BtnLimpar.addActionListener(this::BtnLimparActionPerformed);

        BtnCalcCon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnCalcCon.setForeground(java.awt.Color.blue);
        BtnCalcCon.setText("Calcular Consumo");
        BtnCalcCon.addActionListener(this::BtnCalcConActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblCombustivel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtDistancia)
                    .addComponent(TxtCombustivel)
                    .addComponent(LblDistancia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LblCalcCon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LblConsumo, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                    .addComponent(TxtConsumo)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BtnCalcCon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(LblCalcCon, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LblDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LblCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LblConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCalcCon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtCombustivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCombustivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCombustivelActionPerformed

    private void TxtDistanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDistanciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDistanciaActionPerformed

    private void TxtConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtConsumoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtConsumoActionPerformed

    private void BtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimparActionPerformed
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_BtnLimparActionPerformed

    private void BtnCalcConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalcConActionPerformed
        // TODO add your handling code here:
        String str_distancia = TxtDistancia.getText();
        String str_combustivel = TxtCombustivel.getText();
        
        if(str_distancia.contains(","))
            str_distancia = str_distancia.replace(",", ".");
        if(str_combustivel.contains(","))
            str_combustivel = str_combustivel.replace(",", ".");
        
        try
        {
            Consumo con = new Consumo(Double.parseDouble(str_distancia), Double.parseDouble(str_combustivel));
           
            double gasto = con.calculoConsumo();
            String saida = String.format("%.1f", gasto);
            TxtConsumo.setText(saida);
        }
        catch(NumberFormatException e) 
        {
            JOptionPane.showMessageDialog(null,"Erro: distância e/ou combustível em formato inválido", 
                    "Erro", JOptionPane.ERROR_MESSAGE);
            limpar();
        }
    }//GEN-LAST:event_BtnCalcConActionPerformed

    public void limpar()
    {
        TxtDistancia.setText(null);
        TxtCombustivel.setText(null);
	TxtConsumo.setText(null);
        TxtDistancia.requestFocus();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConsumoForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCalcCon;
    private javax.swing.JButton BtnLimpar;
    private javax.swing.JLabel LblCalcCon;
    private javax.swing.JLabel LblCombustivel;
    private javax.swing.JLabel LblConsumo;
    private javax.swing.JLabel LblDistancia;
    private javax.swing.JTextField TxtCombustivel;
    private javax.swing.JTextField TxtConsumo;
    private javax.swing.JTextField TxtDistancia;
    // End of variables declaration//GEN-END:variables
}
